// 游戏列表配置
export interface GameInfo {
  id: string
  name: string
  description: string
  icon: string
  route: string
  color: string
  difficulty: '简单' | '中等' | '困难'
  category: string
  zone: string // 游戏区域
}

export type GameZone = '休闲区' | '战争策略' | '棋牌' | '益智' | '动作'

export const GAME_ZONES: { id: GameZone; name: string; icon: string; color: string }[] = [
  { id: '休闲区', name: '休闲区', icon: '🎮', color: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)' },
  { id: '战争策略', name: '战争策略', icon: '⚔️', color: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)' },
  { id: '棋牌', name: '棋牌', icon: '🃏', color: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)' },
  { id: '益智', name: '益智', icon: '🧩', color: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)' },
  { id: '动作', name: '动作', icon: '🎯', color: 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)' },
]

export const GAMES: GameInfo[] = [
  // 休闲区
  {
    id: 'snake',
    name: '贪吃蛇',
    description: '控制小蛇吃食物，小心不要撞到自己！',
    icon: '🐍',
    route: '/games/snake',
    color: 'linear-gradient(135deg, #4CAF50 0%, #2E7D32 100%)',
    difficulty: '简单',
    category: '休闲',
    zone: '休闲区',
  },
  {
    id: 'match3',
    name: '消消乐',
    description: '交换方块消除三个或更多相同颜色，获得高分！',
    icon: '💎',
    route: '/games/match3',
    color: 'linear-gradient(135deg, #F093FB 0%, #F5576C 100%)',
    difficulty: '简单',
    category: '休闲',
    zone: '休闲区',
  },
  {
    id: 'gold-miner',
    name: '黄金矿工',
    description: '使用钩子抓取黄金和宝石，挑战更高分数！',
    icon: '⛏️',
    route: '/games/gold-miner',
    color: 'linear-gradient(135deg, #FFD700 0%, #FFA500 100%)',
    difficulty: '中等',
    category: '街机',
    zone: '休闲区',
  },
  {
    id: 'flappy-bird',
    name: '像素鸟',
    description: '控制小鸟穿越障碍，挑战你的反应速度！',
    icon: '🐦',
    route: '/games/flappy-bird',
    color: 'linear-gradient(135deg, #FFE066 0%, #FF6B6B 100%)',
    difficulty: '中等',
    category: '休闲',
    zone: '休闲区',
  },
  {
    id: 'fruit-ninja',
    name: '水果忍者',
    description: '滑动屏幕切水果，小心炸弹！',
    icon: '🍉',
    route: '/games/fruit-ninja',
    color: 'linear-gradient(135deg, #FF6B6B 0%, #FF8E53 100%)',
    difficulty: '简单',
    category: '休闲',
    zone: '休闲区',
  },
  
  // 战争策略
  {
    id: 'airplane',
    name: '飞机大战',
    description: '控制飞机躲避敌机并射击，挑战更高分数！',
    icon: '✈️',
    route: '/games/airplane',
    color: 'linear-gradient(135deg, #00D2FF 0%, #3A7BD5 100%)',
    difficulty: '困难',
    category: '动作',
    zone: '战争策略',
  },
  {
    id: 'tower-defense',
    name: '塔防',
    description: '建造防御塔阻止敌人入侵，制定最佳策略！',
    icon: '🏰',
    route: '/games/tower-defense',
    color: 'linear-gradient(135deg, #8B4513 0%, #A0522D 100%)',
    difficulty: '困难',
    category: '策略',
    zone: '战争策略',
  },
  {
    id: 'battleship',
    name: '战舰',
    description: '猜测对手战舰位置，击沉所有敌舰！',
    icon: '🚢',
    route: '/games/battleship',
    color: 'linear-gradient(135deg, #1e3c72 0%, #2a5298 100%)',
    difficulty: '中等',
    category: '策略',
    zone: '战争策略',
  },
  {
    id: 'chess-war',
    name: '象棋大战',
    description: '经典象棋对战，考验你的战术思维！',
    icon: '♟️',
    route: '/games/chess-war',
    color: 'linear-gradient(135deg, #2c3e50 0%, #34495e 100%)',
    difficulty: '困难',
    category: '策略',
    zone: '战争策略',
  },
  
  // 棋牌
  {
    id: 'poker',
    name: '德州扑克',
    description: '经典德州扑克，考验你的运气和策略！',
    icon: '🃏',
    route: '/games/poker',
    color: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)',
    difficulty: '中等',
    category: '棋牌',
    zone: '棋牌',
  },
  {
    id: 'blackjack',
    name: '21点',
    description: '经典21点游戏，接近21点但不要超过！',
    icon: '🂡',
    route: '/games/blackjack',
    color: 'linear-gradient(135deg, #0f2027 0%, #203a43 100%)',
    difficulty: '简单',
    category: '棋牌',
    zone: '棋牌',
  },
  {
    id: 'mahjong',
    name: '麻将',
    description: '经典麻将游戏，凑成顺子或刻子！',
    icon: '🀄',
    route: '/games/mahjong',
    color: 'linear-gradient(135deg, #c94b4b 0%, #4b134f 100%)',
    difficulty: '中等',
    category: '棋牌',
    zone: '棋牌',
  },
  {
    id: 'solitaire',
    name: '纸牌接龙',
    description: '经典纸牌接龙游戏，将所有牌按顺序排列！',
    icon: '🂮',
    route: '/games/solitaire',
    color: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    difficulty: '简单',
    category: '棋牌',
    zone: '棋牌',
  },
  
  // 益智
  {
    id: 'tetris',
    name: '俄罗斯方块',
    description: '消除完整的行，挑战你的反应速度！',
    icon: '🧩',
    route: '/games/tetris',
    color: 'linear-gradient(135deg, #2196F3 0%, #0D47A1 100%)',
    difficulty: '困难',
    category: '益智',
    zone: '益智',
  },
  {
    id: 'game2048',
    name: '2048',
    description: '滑动合并数字方块，挑战达到2048！',
    icon: '🔢',
    route: '/games/2048',
    color: 'linear-gradient(135deg, #FF6B6B 0%, #C92A2A 100%)',
    difficulty: '中等',
    category: '益智',
    zone: '益智',
  },
  {
    id: 'sudoku',
    name: '数独',
    description: '经典数独游戏，填入1-9使每行每列每宫不重复！',
    icon: '🔢',
    route: '/games/sudoku',
    color: 'linear-gradient(135deg, #fbc531 0%, #e55039 100%)',
    difficulty: '困难',
    category: '益智',
    zone: '益智',
  },
  {
    id: 'memory',
    name: '记忆翻牌',
    description: '翻牌配对，考验你的记忆力！',
    icon: '🧠',
    route: '/games/memory',
    color: 'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)',
    difficulty: '中等',
    category: '益智',
    zone: '益智',
  },
  
  // 动作
  {
    id: 'breakout',
    name: '打砖块',
    description: '用球击碎所有砖块，考验你的精准度！',
    icon: '🎯',
    route: '/games/breakout',
    color: 'linear-gradient(135deg, #E91E63 0%, #880E4F 100%)',
    difficulty: '中等',
    category: '动作',
    zone: '动作',
  },
  {
    id: 'racing',
    name: '赛车',
    description: '控制赛车躲避障碍，挑战最高速度！',
    icon: '🏎️',
    route: '/games/racing',
    color: 'linear-gradient(135deg, #ff6b6b 0%, #ee5a6f 100%)',
    difficulty: '困难',
    category: '动作',
    zone: '动作',
  },
  {
    id: 'platformer',
    name: '平台跳跃',
    description: '控制角色跳跃平台，收集金币到达终点！',
    icon: '🦘',
    route: '/games/platformer',
    color: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
    difficulty: '中等',
    category: '动作',
    zone: '动作',
  },
]
